datasets:
  raw:
    google_search_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}


    sales_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}

    social_media_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data - C.csv
      driver_params: {}

    theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}

    theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}
  
  cleaned:
    google_search_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/google_search_data.parquet
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/product_manufacturer_list.parquet
      driver_params: {}


    sales_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales_data.parquet
      driver_params: {}

    social_media_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/social_media_data - C.parquet
      driver_params: {}

    theme_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_list.parquet
      driver_params: {}

    theme_product_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_product_list.parquet
      driver_params: {}

  train:
      google_search_data:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/google_search_data.csv
        driver_params:
          save:
            index: False
      product_manufacturer_list:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
        driver_params:
          save:
            index: False
      sales_data:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/sales_data.csv
        driver_params:
          save:
            index: False
      social_media_data:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/social_media_data
        driver_params:
          save:
            index: False

      theme_list:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/Theme_list.csv
        driver_params:
          save:
            index: False
      theme_product_list:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/Theme_product_list.csv
        driver_params:
          save:
            index: False
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/google_search_data.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/target.parquet
        driver_params:
          save:
            index: False
  score:
    sales:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/raw/google_search_data.csv
        driver_params:
          save:
            index: False