datasets:
  raw:
    google_search_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}

    sales_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}

    theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}

    theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}

    social_media_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data.csv
      driver_params: {}


  cleaned:

    prod_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/prod_df_clean.parquet
      driver_params: {}

    google_search_data_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/google_search_data_df_clean.parquet
      driver_params: {}
    sales_data_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales_data_df_clean.parquet
      driver_params: {}
    theme_list_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_list_df_clean.parquet
      driver_params: {}
    theme_product_list_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_product_list_df_clean.parquet
      driver_params: {}
    social_media_data_df_clean:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/social_media_data_df_clean.parquet
      driver_params: {}
    # ####
    google_search_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/google_search_data.parquet
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/product_manufacturer_list.parquet
      driver_params: {}


    sales_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales_data.parquet
      driver_params: {}

    social_media_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/social_media_data.parquet
      driver_params: {}

    theme_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_list.parquet
      driver_params: {}

    theme_product_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_product_list.parquet
      driver_params: {}

  processed:
    social_google_sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed/social_google_sales.csv
      driver_params: {}

  train:
    features:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/train/features.parquet
      driver_params:
        save:
          index: False
    target:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/train/target.parquet
      driver_params:
        save:
          index: False

  test:
    features:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/test/features.parquet
      driver_params:
        save:
          index: False
    target:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/test/target.parquet
      driver_params:
        save:
          index: False